
# Scientific publications {#sec-publications}

Please find bellow all scientific publications that our team or collaborators have published right before or during the project timeline. We will keep listing all soil spectroscopy works derived from the SS4GG activities and extended collaborations:

- Safanelli, J. L., Hengl, T., Parente, L. L., Minarik, R., Bloom, D. E., Todd-Brown, K., Gholizadeh, A., Mendes, W. de S., & Sanderman, J. (2025). Open Soil Spectral Library (OSSL): Building reproducible soil calibration models through open development and community engagement. In B. Das (Ed.), PLOS ONE (Vol. 20, Issue 1, p. e0296545). Public Library of Science (PLoS). <https://doi.org/10.1371/journal.pone.0296545>

- Partida, C., Safanelli, J. L., Mitu, S. M., Murad, M. O. F., Ge, Y., Ferguson, R., Shepherd, K., & Sanderman, J. (2025). Building a near-infrared (NIR) soil spectral dataset and predictive machine learning models using a handheld NIR spectrophotometer. In Data in Brief (Vol. 58, p. 111229). Elsevier BV. <https://doi.org/10.1016/j.dib.2024.111229>

- Mitu, S. M., Smith, C., Sanderman, J., Ferguson, R. R., Shepherd, K., & Ge, Y. (2024). Evaluating consistency across multiple NeoSpectra (compact Fourier transform near‐infrared) spectrometers for estimating common soil properties. In Soil Science Society of America Journal (Vol. 88, Issue 4, pp. 1324–1339). Wiley. <https://doi.org/10.1002/saj2.20678>

- Safanelli, J. L., Sanderman, J., Bloom, D., Todd-Brown, K., Parente, L. L., Hengl, T., Adam, S., Albinet, F., Ben-Dor, E., Boot, C. M., Bridson, J. H., Chabrillat, S., Deiss, L., Demattê, J. A. M., Scott Demyan, M., Dercon, G., Doetterl, S., van Egmond, F., Ferguson, R., … Żelazny, W. R. (2023). An interlaboratory comparison of mid-infrared spectra acquisition: Instruments and procedures matter. In Geoderma (Vol. 440, p. 116724). Elsevier BV. <https://doi.org/10.1016/j.geoderma.2023.116724>

- Hong, Y., Sanderman, J., Hengl, T., Chen, S., Wang, N., Xue, J., Zhuo, Z., Peng, J., Li, S., Chen, Y., Liu, Y., Mouazen, A. M., & Shi, Z. (2024). Potential of globally distributed topsoil mid-infrared spectral library for organic carbon estimation. In CATENA (Vol. 235, p. 107628). Elsevier BV. <https://doi.org/10.1016/j.catena.2023.107628>

- Sanderman, J., Smith, C., Safanelli, J. L., Morgan, C. L. S., Ackerson, J., Looker, N., Mathers, C., Keating, R., & Kumar, A. A. (2023). Diffuse reflectance mid-infrared spectroscopy is viable without fine milling. In Soil Security (Vol. 13, p. 100104). Elsevier BV. <https://doi.org/10.1016/j.soisec.2023.100104>

- Sanderman, J., Gholizadeh, A., Pittaki‐Chrysodonta, Z., Huang, J., Safanelli, J. L., & Ferguson, R. (2023). Transferability of a large mid‐infrared soil spectral library between two Fourier‐transform infrared spectrometers. In Soil Science Society of America Journal (Vol. 87, Issue 3, pp. 586–599). Wiley. <https://doi.org/10.1002/saj2.20513>

- Shepherd, K. D., Ferguson, R., Hoover, D., van Egmond, F., Sanderman, J., & Ge, Y. (2022). A global soil spectral calibration library and estimation service. In Soil Security (Vol. 7, p. 100061). Elsevier BV. <https://doi.org/10.1016/j.soisec.2022.100061>

- Sanderman, J., Savage, K., Dangal, S. R. S., Duran, G., Rivard, C., Cavigelli, M. A., Gollany, H. T., Jin, V. L., Liebig, M. A., Omondi, E. C., Rui, Y., & Stewart, C. (2021). Can Agricultural Management Induced Changes in Soil Organic Carbon Be Detected Using Mid-Infrared Spectroscopy? In Remote Sensing (Vol. 13, Issue 12, p. 2265). MDPI AG. <https://doi.org/10.3390/rs13122265>

- Gholizadeh, A., Neumann, C., Chabrillat, S., van Wesemael, B., Castaldi, F., Borůvka, L., Sanderman, J., Klement, A., & Hohmann, C. (2021). Soil organic carbon estimation using VNIR–SWIR spectroscopy: The effect of multiple sensors and scanning conditions. In Soil and Tillage Research (Vol. 211, p. 105017). Elsevier BV. <https://doi.org/10.1016/j.still.2021.105017>

- Pittaki‐Chrysodonta, Z., Hartemink, A. E., Sanderman, J., Ge, Y., & Huang, J. (2021). Evaluating three calibration transfer methods for predictions of soil properties using mid‐infrared spectroscopy. In Soil Science Society of America Journal (Vol. 85, Issue 3, pp. 501–519). Wiley. <https://doi.org/10.1002/saj2.20225>

- Dangal, S. R. S., & Sanderman, J. (2020). Is Standardization Necessary for Sharing of a Large Mid-Infrared Soil Spectral Library? In Sensors (Vol. 20, Issue 23, p. 6729). MDPI AG. <https://doi.org/10.3390/s20236729>

- Sanderman, J., Savage, K., & Dangal, S. R. S. (2020). Mid‐infrared spectroscopy for prediction of soil health indicators in the United States. In Soil Science Society of America Journal (Vol. 84, Issue 1, pp. 251–261). Wiley. <https://doi.org/10.1002/saj2.20009>

- Dangal, S. R. S., Sanderman, J., Wills, S., & Ramirez-Lopez, L. (2019). Accurate and Precise Prediction of Soil Properties from a Large Mid-Infrared Spectral Library. In Soil Systems (Vol. 3, Issue 1, p. 11). MDPI AG. <https://doi.org/10.3390/soilsystems3010011>
