<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Reference soil spectroscopy models | Open Soil Spectral Library</title>
  <meta name="description" content="Open Soil Spectroscopy Library technical documentation. Use these documentation to access OSSL data, fit models, callibrate own models and extend beyond." />
  <meta name="generator" content="bookdown 0.22.2 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Reference soil spectroscopy models | Open Soil Spectral Library" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://soilspectroscopy.github.io/ossl-manual" />
  <meta property="og:image" content="http://soilspectroscopy.github.io/ossl-manual/img/Spectroscopy-Schematic.jpeg" />
  <meta property="og:description" content="Open Soil Spectroscopy Library technical documentation. Use these documentation to access OSSL data, fit models, callibrate own models and extend beyond." />
  <meta name="github-repo" content="soilspectroscopy/ossl-manual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Reference soil spectroscopy models | Open Soil Spectral Library" />
  <meta name="twitter:site" content="@soilspec" />
  <meta name="twitter:description" content="Open Soil Spectroscopy Library technical documentation. Use these documentation to access OSSL data, fit models, callibrate own models and extend beyond." />
  <meta name="twitter:image" content="http://soilspectroscopy.github.io/ossl-manual/img/Spectroscopy-Schematic.jpeg" />

<meta name="author" content="Woodwell Climate Research Center, University of Florida, OpenGeoHub and contributors" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="database.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.8.1/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Open Soil Spectral Library</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#soil-spectroscopy-for-global-good"><i class="fa fa-check"></i><b>1.1</b> Soil Spectroscopy for Global Good</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#what-is-soil-spectroscopy"><i class="fa fa-check"></i><b>1.2</b> What is soil spectroscopy?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#open-soil-spectral-library"><i class="fa fa-check"></i><b>1.3</b> Open Soil Spectral Library</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#ossl-mongodb"><i class="fa fa-check"></i><b>1.4</b> OSSL mongoDB</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#target-variables-of-interest"><i class="fa fa-check"></i><b>1.5</b> Target variables of interest</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#contributing-data"><i class="fa fa-check"></i><b>1.6</b> Contributing data</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#contributing-documentation"><i class="fa fa-check"></i><b>1.7</b> Contributing documentation</a></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i><b>1.8</b> Contributors</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>1.9</b> Disclaimer</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#licence"><i class="fa fa-check"></i><b>1.10</b> Licence</a></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#suggested-literature"><i class="fa fa-check"></i><b>1.11</b> Suggested literature</a></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i><b>1.12</b> Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="new-to-markdown-start-here.html"><a href="new-to-markdown-start-here.html"><i class="fa fa-check"></i><b>2</b> New to markdown. Start here</a>
<ul>
<li class="chapter" data-level="2.1" data-path="new-to-markdown-start-here.html"><a href="new-to-markdown-start-here.html#clone-add-reference-submit-merge-request"><i class="fa fa-check"></i><b>2.1</b> Clone, add reference, submit merge request…</a></li>
<li class="chapter" data-level="2.2" data-path="new-to-markdown-start-here.html"><a href="new-to-markdown-start-here.html#video-course-getting-started-with-r"><i class="fa fa-check"></i><b>2.2</b> Video Course: Getting started with R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html"><i class="fa fa-check"></i><b>3</b> Soil spectroscopy tools and users</a>
<ul>
<li class="chapter" data-level="3.1" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#soil-spectroscopy-instruments"><i class="fa fa-check"></i><b>3.1</b> Soil Spectroscopy Instruments</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#bruker-alpha-1_ft-mir_zn-se"><i class="fa fa-check"></i><b>3.1.1</b> Bruker Alpha 1_FT-MIR_Zn Se</a></li>
<li class="chapter" data-level="3.1.2" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#bruker-alpha-1_ft-mir_kbr"><i class="fa fa-check"></i><b>3.1.2</b> Bruker Alpha 1_FT-MIR_KBr</a></li>
<li class="chapter" data-level="3.1.3" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#bruker-vertex-70-with-hts-xt-accessory"><i class="fa fa-check"></i><b>3.1.3</b> Bruker Vertex 70 with HTS-XT accessory</a></li>
<li class="chapter" data-level="3.1.4" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#asd-labspec-2500-with-muglight-accessory"><i class="fa fa-check"></i><b>3.1.4</b> ASD Labspec 2500 with Muglight accessory</a></li>
<li class="chapter" data-level="3.1.5" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#asd-fieldspec-fr"><i class="fa fa-check"></i><b>3.1.5</b> ASD FieldSpec FR</a></li>
<li class="chapter" data-level="3.1.6" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#xds-rapid-content-analyzer"><i class="fa fa-check"></i><b>3.1.6</b> XDS Rapid Content Analyzer</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#registered-soil-spectral-libraries"><i class="fa fa-check"></i><b>3.2</b> Registered soil spectral libraries</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#kssl.ssl"><i class="fa fa-check"></i><b>3.2.1</b> KSSL.SSL</a></li>
<li class="chapter" data-level="3.2.2" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#icraf.isric"><i class="fa fa-check"></i><b>3.2.2</b> ICRAF.ISRIC</a></li>
<li class="chapter" data-level="3.2.3" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#lucas.ssl"><i class="fa fa-check"></i><b>3.2.3</b> LUCAS.SSL</a></li>
<li class="chapter" data-level="3.2.4" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#afsis1.ssl"><i class="fa fa-check"></i><b>3.2.4</b> AFSIS1.SSL</a></li>
<li class="chapter" data-level="3.2.5" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#caf.ssl"><i class="fa fa-check"></i><b>3.2.5</b> CAF.SSL</a></li>
<li class="chapter" data-level="3.2.6" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#neon.ssl"><i class="fa fa-check"></i><b>3.2.6</b> NEON.SSL</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#soil-spetroscopy-organizations"><i class="fa fa-check"></i><b>3.3</b> Soil spetroscopy organizations</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#kssl"><i class="fa fa-check"></i><b>3.3.1</b> KSSL</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#soil-spectroscopy-software"><i class="fa fa-check"></i><b>3.4</b> Soil Spectroscopy software</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#asdreader"><i class="fa fa-check"></i><b>3.4.1</b> asdreader</a></li>
<li class="chapter" data-level="3.4.2" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#prospectr"><i class="fa fa-check"></i><b>3.4.2</b> prospectr</a></li>
<li class="chapter" data-level="3.4.3" data-path="soil-spectroscopy-tools-and-users.html"><a href="soil-spectroscopy-tools-and-users.html#simplerspec"><i class="fa fa-check"></i><b>3.4.3</b> simplerspec</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="database.html"><a href="database.html"><i class="fa fa-check"></i><b>4</b> Database</a>
<ul>
<li class="chapter" data-level="4.1" data-path="database.html"><a href="database.html#sites-table"><i class="fa fa-check"></i><b>4.1</b> Sites table</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="database.html"><a href="database.html#id.layer_uuid_c"><i class="fa fa-check"></i><b>4.1.1</b> id.layer_uuid_c</a></li>
<li class="chapter" data-level="4.1.2" data-path="database.html"><a href="database.html#id.location_olc_c"><i class="fa fa-check"></i><b>4.1.2</b> id.location_olc_c</a></li>
<li class="chapter" data-level="4.1.3" data-path="database.html"><a href="database.html#observation.ogc.schema.title_ogc_txt"><i class="fa fa-check"></i><b>4.1.3</b> observation.ogc.schema.title_ogc_txt</a></li>
<li class="chapter" data-level="4.1.4" data-path="database.html"><a href="database.html#observation.ogc.schema_idn_url"><i class="fa fa-check"></i><b>4.1.4</b> observation.ogc.schema_idn_url</a></li>
<li class="chapter" data-level="4.1.5" data-path="database.html"><a href="database.html#observation.date.begin_iso.8601_yyyy.mm.dd"><i class="fa fa-check"></i><b>4.1.5</b> observation.date.begin_iso.8601_yyyy.mm.dd</a></li>
<li class="chapter" data-level="4.1.6" data-path="database.html"><a href="database.html#observation.date.end_iso.8601_yyyy.mm.dd"><i class="fa fa-check"></i><b>4.1.6</b> observation.date.end_iso.8601_yyyy.mm.dd</a></li>
<li class="chapter" data-level="4.1.7" data-path="database.html"><a href="database.html#location.address_utf8_txt"><i class="fa fa-check"></i><b>4.1.7</b> location.address_utf8_txt</a></li>
<li class="chapter" data-level="4.1.8" data-path="database.html"><a href="database.html#location.country_iso.3166_c"><i class="fa fa-check"></i><b>4.1.8</b> location.country_iso.3166_c</a></li>
<li class="chapter" data-level="4.1.9" data-path="database.html"><a href="database.html#location.method_any_c"><i class="fa fa-check"></i><b>4.1.9</b> location.method_any_c</a></li>
<li class="chapter" data-level="4.1.10" data-path="database.html"><a href="database.html#surveyor.title_utf8_txt"><i class="fa fa-check"></i><b>4.1.10</b> surveyor.title_utf8_txt</a></li>
<li class="chapter" data-level="4.1.11" data-path="database.html"><a href="database.html#surveyor.contact_ietf_email"><i class="fa fa-check"></i><b>4.1.11</b> surveyor.contact_ietf_email</a></li>
<li class="chapter" data-level="4.1.12" data-path="database.html"><a href="database.html#surveyor.address_utf8_txt"><i class="fa fa-check"></i><b>4.1.12</b> surveyor.address_utf8_txt</a></li>
<li class="chapter" data-level="4.1.13" data-path="database.html"><a href="database.html#longitude_wgs84_dd"><i class="fa fa-check"></i><b>4.1.13</b> longitude_wgs84_dd</a></li>
<li class="chapter" data-level="4.1.14" data-path="database.html"><a href="database.html#latitude_wgs84_dd"><i class="fa fa-check"></i><b>4.1.14</b> latitude_wgs84_dd</a></li>
<li class="chapter" data-level="4.1.15" data-path="database.html"><a href="database.html#location.error_any_m"><i class="fa fa-check"></i><b>4.1.15</b> location.error_any_m</a></li>
<li class="chapter" data-level="4.1.16" data-path="database.html"><a href="database.html#dataset.title_utf8_txt"><i class="fa fa-check"></i><b>4.1.16</b> dataset.title_utf8_txt</a></li>
<li class="chapter" data-level="4.1.17" data-path="database.html"><a href="database.html#dataset.owner_utf8_txt"><i class="fa fa-check"></i><b>4.1.17</b> dataset.owner_utf8_txt</a></li>
<li class="chapter" data-level="4.1.18" data-path="database.html"><a href="database.html#dataset.code_ascii_txt"><i class="fa fa-check"></i><b>4.1.18</b> dataset.code_ascii_txt</a></li>
<li class="chapter" data-level="4.1.19" data-path="database.html"><a href="database.html#dataset.address_idn_url"><i class="fa fa-check"></i><b>4.1.19</b> dataset.address_idn_url</a></li>
<li class="chapter" data-level="4.1.20" data-path="database.html"><a href="database.html#dataset.license.title_ascii_txt"><i class="fa fa-check"></i><b>4.1.20</b> dataset.license.title_ascii_txt</a></li>
<li class="chapter" data-level="4.1.21" data-path="database.html"><a href="database.html#dataset.license.address_idn_url"><i class="fa fa-check"></i><b>4.1.21</b> dataset.license.address_idn_url</a></li>
<li class="chapter" data-level="4.1.22" data-path="database.html"><a href="database.html#dataset.doi_idf_c"><i class="fa fa-check"></i><b>4.1.22</b> dataset.doi_idf_c</a></li>
<li class="chapter" data-level="4.1.23" data-path="database.html"><a href="database.html#dataset.contact.name_utf8_txt"><i class="fa fa-check"></i><b>4.1.23</b> dataset.contact.name_utf8_txt</a></li>
<li class="chapter" data-level="4.1.24" data-path="database.html"><a href="database.html#dataset.contact.email_ietf_email"><i class="fa fa-check"></i><b>4.1.24</b> dataset.contact.email_ietf_email</a></li>
<li class="chapter" data-level="4.1.25" data-path="database.html"><a href="database.html#id.dataset.site_ascii_c"><i class="fa fa-check"></i><b>4.1.25</b> id.dataset.site_ascii_c</a></li>
<li class="chapter" data-level="4.1.26" data-path="database.html"><a href="database.html#id.user.site_ascii_c"><i class="fa fa-check"></i><b>4.1.26</b> id.user.site_ascii_c</a></li>
<li class="chapter" data-level="4.1.27" data-path="database.html"><a href="database.html#id.project_ascii_c"><i class="fa fa-check"></i><b>4.1.27</b> id.project_ascii_c</a></li>
<li class="chapter" data-level="4.1.28" data-path="database.html"><a href="database.html#pedon.taxa_usda_c"><i class="fa fa-check"></i><b>4.1.28</b> pedon.taxa_usda_c</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="database.html"><a href="database.html#soillab-table"><i class="fa fa-check"></i><b>4.2</b> Soillab table</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="database.html"><a href="database.html#id.layer_uuid_c-1"><i class="fa fa-check"></i><b>4.2.1</b> id.layer_uuid_c</a></li>
<li class="chapter" data-level="4.2.2" data-path="database.html"><a href="database.html#id.layer_local_c"><i class="fa fa-check"></i><b>4.2.2</b> id.layer_local_c</a></li>
<li class="chapter" data-level="4.2.3" data-path="database.html"><a href="database.html#sample.doi_idf_c"><i class="fa fa-check"></i><b>4.2.3</b> sample.doi_idf_c</a></li>
<li class="chapter" data-level="4.2.4" data-path="database.html"><a href="database.html#layer.sequence_usda_uint16"><i class="fa fa-check"></i><b>4.2.4</b> layer.sequence_usda_uint16</a></li>
<li class="chapter" data-level="4.2.5" data-path="database.html"><a href="database.html#layer.type_usda_c"><i class="fa fa-check"></i><b>4.2.5</b> layer.type_usda_c</a></li>
<li class="chapter" data-level="4.2.6" data-path="database.html"><a href="database.html#layer.field.label_any_c"><i class="fa fa-check"></i><b>4.2.6</b> layer.field.label_any_c</a></li>
<li class="chapter" data-level="4.2.7" data-path="database.html"><a href="database.html#layer.upper.depth_usda_cm"><i class="fa fa-check"></i><b>4.2.7</b> layer.upper.depth_usda_cm</a></li>
<li class="chapter" data-level="4.2.8" data-path="database.html"><a href="database.html#layer.lower.depth_usda_cm"><i class="fa fa-check"></i><b>4.2.8</b> layer.lower.depth_usda_cm</a></li>
<li class="chapter" data-level="4.2.9" data-path="database.html"><a href="database.html#horizon.designation_usda_c"><i class="fa fa-check"></i><b>4.2.9</b> horizon.designation_usda_c</a></li>
<li class="chapter" data-level="4.2.10" data-path="database.html"><a href="database.html#horizon.designation.discontinuity_usda_c"><i class="fa fa-check"></i><b>4.2.10</b> horizon.designation.discontinuity_usda_c</a></li>
<li class="chapter" data-level="4.2.11" data-path="database.html"><a href="database.html#layer.structure.type_usda_c"><i class="fa fa-check"></i><b>4.2.11</b> layer.structure.type_usda_c</a></li>
<li class="chapter" data-level="4.2.12" data-path="database.html"><a href="database.html#layer.structure.grade_usda_c"><i class="fa fa-check"></i><b>4.2.12</b> layer.structure.grade_usda_c</a></li>
<li class="chapter" data-level="4.2.13" data-path="database.html"><a href="database.html#layer.texture_usda_c"><i class="fa fa-check"></i><b>4.2.13</b> layer.texture_usda_c</a></li>
<li class="chapter" data-level="4.2.14" data-path="database.html"><a href="database.html#agg.stb_usda.1b1_wpct"><i class="fa fa-check"></i><b>4.2.14</b> agg.stb_usda.1b1_wpct</a></li>
<li class="chapter" data-level="4.2.15" data-path="database.html"><a href="database.html#al.dith_usda.4g1_wpct"><i class="fa fa-check"></i><b>4.2.15</b> al.dith_usda.4g1_wpct</a></li>
<li class="chapter" data-level="4.2.16" data-path="database.html"><a href="database.html#al.kcl_usda.4b3_cmolkg"><i class="fa fa-check"></i><b>4.2.16</b> al.kcl_usda.4b3_cmolkg</a></li>
<li class="chapter" data-level="4.2.17" data-path="database.html"><a href="database.html#al.ox_usda.4g2_wpct"><i class="fa fa-check"></i><b>4.2.17</b> al.ox_usda.4g2_wpct</a></li>
<li class="chapter" data-level="4.2.18" data-path="database.html"><a href="database.html#al.pyp_usda.4g3_wpct"><i class="fa fa-check"></i><b>4.2.18</b> al.pyp_usda.4g3_wpct</a></li>
<li class="chapter" data-level="4.2.19" data-path="database.html"><a href="database.html#alsat_usda.4b4_wpct"><i class="fa fa-check"></i><b>4.2.19</b> alsat_usda.4b4_wpct</a></li>
<li class="chapter" data-level="4.2.20" data-path="database.html"><a href="database.html#bd.clod_usda.3b1_gcm3"><i class="fa fa-check"></i><b>4.2.20</b> bd.clod_usda.3b1_gcm3</a></li>
<li class="chapter" data-level="4.2.21" data-path="database.html"><a href="database.html#bd.core_iso.11272.2017_gcm3"><i class="fa fa-check"></i><b>4.2.21</b> bd.core_iso.11272.2017_gcm3</a></li>
<li class="chapter" data-level="4.2.22" data-path="database.html"><a href="database.html#bd.od_usda.3b2_gcm3"><i class="fa fa-check"></i><b>4.2.22</b> bd.od_usda.3b2_gcm3</a></li>
<li class="chapter" data-level="4.2.23" data-path="database.html"><a href="database.html#bsat_usda.4b4_wpct"><i class="fa fa-check"></i><b>4.2.23</b> bsat_usda.4b4_wpct</a></li>
<li class="chapter" data-level="4.2.24" data-path="database.html"><a href="database.html#c.tot_iso.10694.1995_wpct"><i class="fa fa-check"></i><b>4.2.24</b> c.tot_iso.10694.1995_wpct</a></li>
<li class="chapter" data-level="4.2.25" data-path="database.html"><a href="database.html#c.tot_usda.4h2_wpct"><i class="fa fa-check"></i><b>4.2.25</b> c.tot_usda.4h2_wpct</a></li>
<li class="chapter" data-level="4.2.26" data-path="database.html"><a href="database.html#ca.ext_usda.4b1_cmolkg"><i class="fa fa-check"></i><b>4.2.26</b> ca.ext_usda.4b1_cmolkg</a></li>
<li class="chapter" data-level="4.2.27" data-path="database.html"><a href="database.html#caco3_iso.10693.1995_vpct"><i class="fa fa-check"></i><b>4.2.27</b> caco3_iso.10693.1995_vpct</a></li>
<li class="chapter" data-level="4.2.28" data-path="database.html"><a href="database.html#caco3_usda.4e1_wpct"><i class="fa fa-check"></i><b>4.2.28</b> caco3_usda.4e1_wpct</a></li>
<li class="chapter" data-level="4.2.29" data-path="database.html"><a href="database.html#caco3.pres_usda.1b1_c"><i class="fa fa-check"></i><b>4.2.29</b> caco3.pres_usda.1b1_c</a></li>
<li class="chapter" data-level="4.2.30" data-path="database.html"><a href="database.html#cec.ext_iso.13536.1995_cmolkg"><i class="fa fa-check"></i><b>4.2.30</b> cec.ext_iso.13536.1995_cmolkg</a></li>
<li class="chapter" data-level="4.2.31" data-path="database.html"><a href="database.html#cec.ext_usda.4b1_cmolkg"><i class="fa fa-check"></i><b>4.2.31</b> cec.ext_usda.4b1_cmolkg</a></li>
<li class="chapter" data-level="4.2.32" data-path="database.html"><a href="database.html#clay.tot_iso.11277.2020_wpct"><i class="fa fa-check"></i><b>4.2.32</b> clay.tot_iso.11277.2020_wpct</a></li>
<li class="chapter" data-level="4.2.33" data-path="database.html"><a href="database.html#clay.tot_usda.3a1_wpct"><i class="fa fa-check"></i><b>4.2.33</b> clay.tot_usda.3a1_wpct</a></li>
<li class="chapter" data-level="4.2.34" data-path="database.html"><a href="database.html#ec.ext.sat_usda.4f2_dsm"><i class="fa fa-check"></i><b>4.2.34</b> ec.ext.sat_usda.4f2_dsm</a></li>
<li class="chapter" data-level="4.2.35" data-path="database.html"><a href="database.html#ec.w_usda.4f1_dsm"><i class="fa fa-check"></i><b>4.2.35</b> ec.w_usda.4f1_dsm</a></li>
<li class="chapter" data-level="4.2.36" data-path="database.html"><a href="database.html#ecec_usda.4b4_cmolkg"><i class="fa fa-check"></i><b>4.2.36</b> ecec_usda.4b4_cmolkg</a></li>
<li class="chapter" data-level="4.2.37" data-path="database.html"><a href="database.html#fe.dith_usda.4g1_wpct"><i class="fa fa-check"></i><b>4.2.37</b> fe.dith_usda.4g1_wpct</a></li>
<li class="chapter" data-level="4.2.38" data-path="database.html"><a href="database.html#fe.ox_usda.4g2_wpct"><i class="fa fa-check"></i><b>4.2.38</b> fe.ox_usda.4g2_wpct</a></li>
<li class="chapter" data-level="4.2.39" data-path="database.html"><a href="database.html#fe.pyp_usda.4g3_wpct"><i class="fa fa-check"></i><b>4.2.39</b> fe.pyp_usda.4g3_wpct</a></li>
<li class="chapter" data-level="4.2.40" data-path="database.html"><a href="database.html#gyp_usda.4e2_wpct"><i class="fa fa-check"></i><b>4.2.40</b> gyp_usda.4e2_wpct</a></li>
<li class="chapter" data-level="4.2.41" data-path="database.html"><a href="database.html#humus_usda.4h2_wpct"><i class="fa fa-check"></i><b>4.2.41</b> humus_usda.4h2_wpct</a></li>
<li class="chapter" data-level="4.2.42" data-path="database.html"><a href="database.html#k.ext_usda.4b1_cmolkg"><i class="fa fa-check"></i><b>4.2.42</b> k.ext_usda.4b1_cmolkg</a></li>
<li class="chapter" data-level="4.2.43" data-path="database.html"><a href="database.html#mg.ext_usda.4b1_cmolkg"><i class="fa fa-check"></i><b>4.2.43</b> mg.ext_usda.4b1_cmolkg</a></li>
<li class="chapter" data-level="4.2.44" data-path="database.html"><a href="database.html#n.tot_iso.13878.1998_wpct"><i class="fa fa-check"></i><b>4.2.44</b> n.tot_iso.13878.1998_wpct</a></li>
<li class="chapter" data-level="4.2.45" data-path="database.html"><a href="database.html#n.tot_usda.4h2_wpct"><i class="fa fa-check"></i><b>4.2.45</b> n.tot_usda.4h2_wpct</a></li>
<li class="chapter" data-level="4.2.46" data-path="database.html"><a href="database.html#na.exch_usda.4f3_wpct"><i class="fa fa-check"></i><b>4.2.46</b> na.exch_usda.4f3_wpct</a></li>
<li class="chapter" data-level="4.2.47" data-path="database.html"><a href="database.html#na.ext_usda.4b1_cmolkg"><i class="fa fa-check"></i><b>4.2.47</b> na.ext_usda.4b1_cmolkg</a></li>
<li class="chapter" data-level="4.2.48" data-path="database.html"><a href="database.html#oc_iso.10694.1995_wpct"><i class="fa fa-check"></i><b>4.2.48</b> oc_iso.10694.1995_wpct</a></li>
<li class="chapter" data-level="4.2.49" data-path="database.html"><a href="database.html#oc_iso.17184.2014_wpct"><i class="fa fa-check"></i><b>4.2.49</b> oc_iso.17184.2014_wpct</a></li>
<li class="chapter" data-level="4.2.50" data-path="database.html"><a href="database.html#oc_usda.4h2_wpct"><i class="fa fa-check"></i><b>4.2.50</b> oc_usda.4h2_wpct</a></li>
<li class="chapter" data-level="4.2.51" data-path="database.html"><a href="database.html#oc_usda.calc_wpct"><i class="fa fa-check"></i><b>4.2.51</b> oc_usda.calc_wpct</a></li>
<li class="chapter" data-level="4.2.52" data-path="database.html"><a href="database.html#p.ext_usda.4d6_mgkg"><i class="fa fa-check"></i><b>4.2.52</b> p.ext_usda.4d6_mgkg</a></li>
<li class="chapter" data-level="4.2.53" data-path="database.html"><a href="database.html#p.olsn_usda.4d5_mgkg"><i class="fa fa-check"></i><b>4.2.53</b> p.olsn_usda.4d5_mgkg</a></li>
<li class="chapter" data-level="4.2.54" data-path="database.html"><a href="database.html#ph.cacl2_iso.10390.1994_index"><i class="fa fa-check"></i><b>4.2.54</b> ph.cacl2_iso.10390.1994_index</a></li>
<li class="chapter" data-level="4.2.55" data-path="database.html"><a href="database.html#ph.cacl2_usda.4c1_index"><i class="fa fa-check"></i><b>4.2.55</b> ph.cacl2_usda.4c1_index</a></li>
<li class="chapter" data-level="4.2.56" data-path="database.html"><a href="database.html#ph.h2o_usda.4c1_index"><i class="fa fa-check"></i><b>4.2.56</b> ph.h2o_usda.4c1_index</a></li>
<li class="chapter" data-level="4.2.57" data-path="database.html"><a href="database.html#s.tot_usda.4h2_wpct"><i class="fa fa-check"></i><b>4.2.57</b> s.tot_usda.4h2_wpct</a></li>
<li class="chapter" data-level="4.2.58" data-path="database.html"><a href="database.html#sand.tot_iso.11277.2020_wpct"><i class="fa fa-check"></i><b>4.2.58</b> sand.tot_iso.11277.2020_wpct</a></li>
<li class="chapter" data-level="4.2.59" data-path="database.html"><a href="database.html#sand.tot_usda.3a1_wpct"><i class="fa fa-check"></i><b>4.2.59</b> sand.tot_usda.3a1_wpct</a></li>
<li class="chapter" data-level="4.2.60" data-path="database.html"><a href="database.html#silt.tot_iso.11277.2020_wpct"><i class="fa fa-check"></i><b>4.2.60</b> silt.tot_iso.11277.2020_wpct</a></li>
<li class="chapter" data-level="4.2.61" data-path="database.html"><a href="database.html#silt.tot_usda.3a1_wpct"><i class="fa fa-check"></i><b>4.2.61</b> silt.tot_usda.3a1_wpct</a></li>
<li class="chapter" data-level="4.2.62" data-path="database.html"><a href="database.html#sodium.ads.ratio_usda.4f3_index"><i class="fa fa-check"></i><b>4.2.62</b> sodium.ads.ratio_usda.4f3_index</a></li>
<li class="chapter" data-level="4.2.63" data-path="database.html"><a href="database.html#wpg2_iso.11277.2020_wpct"><i class="fa fa-check"></i><b>4.2.63</b> wpg2_iso.11277.2020_wpct</a></li>
<li class="chapter" data-level="4.2.64" data-path="database.html"><a href="database.html#wpg2_usda.3a2_wpct"><i class="fa fa-check"></i><b>4.2.64</b> wpg2_usda.3a2_wpct</a></li>
<li class="chapter" data-level="4.2.65" data-path="database.html"><a href="database.html#wr.1500kbar_usda.3c2_wpct"><i class="fa fa-check"></i><b>4.2.65</b> wr.1500kbar_usda.3c2_wpct</a></li>
<li class="chapter" data-level="4.2.66" data-path="database.html"><a href="database.html#wr.33kbar_usda.3c1_wpct"><i class="fa fa-check"></i><b>4.2.66</b> wr.33kbar_usda.3c1_wpct</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="database.html"><a href="database.html#mir-table"><i class="fa fa-check"></i><b>4.3</b> MIR scans table</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="database.html"><a href="database.html#id.scan_uuid_c"><i class="fa fa-check"></i><b>4.3.1</b> id.scan_uuid_c</a></li>
<li class="chapter" data-level="4.3.2" data-path="database.html"><a href="database.html#id.scan_local_c"><i class="fa fa-check"></i><b>4.3.2</b> id.scan_local_c</a></li>
<li class="chapter" data-level="4.3.3" data-path="database.html"><a href="database.html#id.layer_uuid_c-2"><i class="fa fa-check"></i><b>4.3.3</b> id.layer_uuid_c</a></li>
<li class="chapter" data-level="4.3.4" data-path="database.html"><a href="database.html#id.layer_local_c-1"><i class="fa fa-check"></i><b>4.3.4</b> id.layer_local_c</a></li>
<li class="chapter" data-level="4.3.5" data-path="database.html"><a href="database.html#model.name_utf8_txt"><i class="fa fa-check"></i><b>4.3.5</b> model.name_utf8_txt</a></li>
<li class="chapter" data-level="4.3.6" data-path="database.html"><a href="database.html#model.code_any_c"><i class="fa fa-check"></i><b>4.3.6</b> model.code_any_c</a></li>
<li class="chapter" data-level="4.3.7" data-path="database.html"><a href="database.html#method.light.source_any_c"><i class="fa fa-check"></i><b>4.3.7</b> method.light.source_any_c</a></li>
<li class="chapter" data-level="4.3.8" data-path="database.html"><a href="database.html#method.preparation_any_c"><i class="fa fa-check"></i><b>4.3.8</b> method.preparation_any_c</a></li>
<li class="chapter" data-level="4.3.9" data-path="database.html"><a href="database.html#scan.file_any_c"><i class="fa fa-check"></i><b>4.3.9</b> scan.file_any_c</a></li>
<li class="chapter" data-level="4.3.10" data-path="database.html"><a href="database.html#scan.date.begin_iso.8601_yyyy.mm.dd"><i class="fa fa-check"></i><b>4.3.10</b> scan.date.begin_iso.8601_yyyy.mm.dd</a></li>
<li class="chapter" data-level="4.3.11" data-path="database.html"><a href="database.html#scan.date.end_iso.8601_yyyy.mm.dd"><i class="fa fa-check"></i><b>4.3.11</b> scan.date.end_iso.8601_yyyy.mm.dd</a></li>
<li class="chapter" data-level="4.3.12" data-path="database.html"><a href="database.html#scan.license.title_ascii_txt"><i class="fa fa-check"></i><b>4.3.12</b> scan.license.title_ascii_txt</a></li>
<li class="chapter" data-level="4.3.13" data-path="database.html"><a href="database.html#scan.license.address_idn_url"><i class="fa fa-check"></i><b>4.3.13</b> scan.license.address_idn_url</a></li>
<li class="chapter" data-level="4.3.14" data-path="database.html"><a href="database.html#scan.doi_idf_c"><i class="fa fa-check"></i><b>4.3.14</b> scan.doi_idf_c</a></li>
<li class="chapter" data-level="4.3.15" data-path="database.html"><a href="database.html#scan.contact.name_utf8_txt"><i class="fa fa-check"></i><b>4.3.15</b> scan.contact.name_utf8_txt</a></li>
<li class="chapter" data-level="4.3.16" data-path="database.html"><a href="database.html#scan.contact.email_ietf_email"><i class="fa fa-check"></i><b>4.3.16</b> scan.contact.email_ietf_email</a></li>
<li class="chapter" data-level="4.3.17" data-path="database.html"><a href="database.html#scan_mir._abs"><i class="fa fa-check"></i><b>4.3.17</b> scan_mir.****_abs</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="database.html"><a href="database.html#visnir-table"><i class="fa fa-check"></i><b>4.4</b> VisNIR scans table</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="database.html"><a href="database.html#id.scan_uuid_c-1"><i class="fa fa-check"></i><b>4.4.1</b> id.scan_uuid_c</a></li>
<li class="chapter" data-level="4.4.2" data-path="database.html"><a href="database.html#id.scan_local_c-1"><i class="fa fa-check"></i><b>4.4.2</b> id.scan_local_c</a></li>
<li class="chapter" data-level="4.4.3" data-path="database.html"><a href="database.html#id.layer_uuid_c-3"><i class="fa fa-check"></i><b>4.4.3</b> id.layer_uuid_c</a></li>
<li class="chapter" data-level="4.4.4" data-path="database.html"><a href="database.html#id.layer_local_c-2"><i class="fa fa-check"></i><b>4.4.4</b> id.layer_local_c</a></li>
<li class="chapter" data-level="4.4.5" data-path="database.html"><a href="database.html#model.name_utf8_txt-1"><i class="fa fa-check"></i><b>4.4.5</b> model.name_utf8_txt</a></li>
<li class="chapter" data-level="4.4.6" data-path="database.html"><a href="database.html#model.code_any_c-1"><i class="fa fa-check"></i><b>4.4.6</b> model.code_any_c</a></li>
<li class="chapter" data-level="4.4.7" data-path="database.html"><a href="database.html#method.light.source_any_c-1"><i class="fa fa-check"></i><b>4.4.7</b> method.light.source_any_c</a></li>
<li class="chapter" data-level="4.4.8" data-path="database.html"><a href="database.html#method.preparation_any_c-1"><i class="fa fa-check"></i><b>4.4.8</b> method.preparation_any_c</a></li>
<li class="chapter" data-level="4.4.9" data-path="database.html"><a href="database.html#scan.file_any_c-1"><i class="fa fa-check"></i><b>4.4.9</b> scan.file_any_c</a></li>
<li class="chapter" data-level="4.4.10" data-path="database.html"><a href="database.html#scan.date.begin_iso.8601_yyyy.mm.dd-1"><i class="fa fa-check"></i><b>4.4.10</b> scan.date.begin_iso.8601_yyyy.mm.dd</a></li>
<li class="chapter" data-level="4.4.11" data-path="database.html"><a href="database.html#scan.date.end_iso.8601_yyyy.mm.dd-1"><i class="fa fa-check"></i><b>4.4.11</b> scan.date.end_iso.8601_yyyy.mm.dd</a></li>
<li class="chapter" data-level="4.4.12" data-path="database.html"><a href="database.html#scan.license.title_ascii_txt-1"><i class="fa fa-check"></i><b>4.4.12</b> scan.license.title_ascii_txt</a></li>
<li class="chapter" data-level="4.4.13" data-path="database.html"><a href="database.html#scan.license.address_idn_url-1"><i class="fa fa-check"></i><b>4.4.13</b> scan.license.address_idn_url</a></li>
<li class="chapter" data-level="4.4.14" data-path="database.html"><a href="database.html#scan.doi_idf_c-1"><i class="fa fa-check"></i><b>4.4.14</b> scan.doi_idf_c</a></li>
<li class="chapter" data-level="4.4.15" data-path="database.html"><a href="database.html#scan.contact.name_utf8_txt-1"><i class="fa fa-check"></i><b>4.4.15</b> scan.contact.name_utf8_txt</a></li>
<li class="chapter" data-level="4.4.16" data-path="database.html"><a href="database.html#scan.contact.email_ietf_email-1"><i class="fa fa-check"></i><b>4.4.16</b> scan.contact.email_ietf_email</a></li>
<li class="chapter" data-level="4.4.17" data-path="database.html"><a href="database.html#scan_visnir._pcnt"><i class="fa fa-check"></i><b>4.4.17</b> scan_visnir.****_pcnt</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="database.html"><a href="database.html#harmonization-rules"><i class="fa fa-check"></i><b>4.5</b> Harmonization rules</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="database.html"><a href="database.html#ph"><i class="fa fa-check"></i><b>4.5.1</b> pH</a></li>
<li class="chapter" data-level="4.5.2" data-path="database.html"><a href="database.html#carbon"><i class="fa fa-check"></i><b>4.5.2</b> Carbon</a></li>
<li class="chapter" data-level="4.5.3" data-path="database.html"><a href="database.html#phosphorous"><i class="fa fa-check"></i><b>4.5.3</b> Phosphorous</a></li>
<li class="chapter" data-level="4.5.4" data-path="database.html"><a href="database.html#potassium"><i class="fa fa-check"></i><b>4.5.4</b> Potassium</a></li>
<li class="chapter" data-level="4.5.5" data-path="database.html"><a href="database.html#nitrogen"><i class="fa fa-check"></i><b>4.5.5</b> Nitrogen</a></li>
<li class="chapter" data-level="4.5.6" data-path="database.html"><a href="database.html#exchangeable-cations-and-cec"><i class="fa fa-check"></i><b>4.5.6</b> Exchangeable cations and CEC</a></li>
<li class="chapter" data-level="4.5.7" data-path="database.html"><a href="database.html#texture-fractions"><i class="fa fa-check"></i><b>4.5.7</b> Texture fractions</a></li>
<li class="chapter" data-level="4.5.8" data-path="database.html"><a href="database.html#bulk-density"><i class="fa fa-check"></i><b>4.5.8</b> Bulk density</a></li>
<li class="chapter" data-level="4.5.9" data-path="database.html"><a href="database.html#soil-biological-variables"><i class="fa fa-check"></i><b>4.5.9</b> Soil biological variables</a></li>
<li class="chapter" data-level="4.5.10" data-path="database.html"><a href="database.html#soil-contaminants"><i class="fa fa-check"></i><b>4.5.10</b> Soil contaminants</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html"><i class="fa fa-check"></i><b>5</b> Reference soil spectroscopy models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#ossl-global-soil-spectroscopy-callibrarion-models"><i class="fa fa-check"></i><b>5.1</b> OSSL global soil spectroscopy callibrarion models</a></li>
<li class="chapter" data-level="5.2" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#using-default-ossl-models-to-predict-soil-properties"><i class="fa fa-check"></i><b>5.2</b> Using default OSSL models to predict soil properties</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#predicting-soil-properties-using-mir-spectra"><i class="fa fa-check"></i><b>5.2.1</b> Predicting soil properties using MIR spectra</a></li>
<li class="chapter" data-level="5.2.2" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#predicting-soil-properties-using-mir-spectra-and-geographical-covariates"><i class="fa fa-check"></i><b>5.2.2</b> Predicting soil properties using MIR spectra and geographical covariates</a></li>
<li class="chapter" data-level="5.2.3" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#predicting-soil-properties-using-visnir-spectra"><i class="fa fa-check"></i><b>5.2.3</b> Predicting soil properties using VisNIR spectra</a></li>
<li class="chapter" data-level="5.2.4" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#importing-soil-spectral-scans-using-raw-data-formats"><i class="fa fa-check"></i><b>5.2.4</b> Importing soil spectral scans using raw data formats</a></li>
<li class="chapter" data-level="5.2.5" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#the-bundle-approach-to-soil-spectroscopy-calibration"><i class="fa fa-check"></i><b>5.2.5</b> The bundle approach to soil spectroscopy calibration</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="reference-soil-spectroscopy-models.html"><a href="reference-soil-spectroscopy-models.html#registering-your-own-model"><i class="fa fa-check"></i><b>5.3</b> Registering your own model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://soilspectroscopy.org">J. (Jon) Sanderman and contributors</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Open Soil Spectral Library</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="reference-soil-spectroscopy-models" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Reference soil spectroscopy models</h1>
<p>The following sections describe steps used to produce OSSL models, which
are used in the OSSL calibration service and API. For more in-depth insight of
the modeling steps please refer to the <a href="https://github.com/soilspectroscopy/ossl-models">ossl-models</a> repository.</p>
<div id="ossl-global-soil-spectroscopy-callibrarion-models" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> OSSL global soil spectroscopy callibrarion models</h2>
<p>We have fitted a number of calibration models using OSSL MIR and VisNIR spectra
and combination of additional covariates, and which are now publicly available
for use under the CC-BY license. For modeling we use the Ensemble Machine Learning
framework as implemented in the R <a href="https://mlr.mlr-org.com/">mlr</a> programming environment
with the following parameters:</p>
<ol style="list-style-type: decimal">
<li>Regression on first 60 Principal Component Analysis PC’s of the raw spectra;<br />
</li>
<li>Four base learners: Random Forest, Gradient Boosting, Cubist and Lasso and Elastic-Net Regularized GLM;<br />
</li>
<li>Ensemble Machine Learning by <a href="https://mlr.mlr-org.com/reference/makeStackedLearner.html">stacking / meta-learner</a> through 5-fold Cross-Validation;<br />
</li>
<li>Blocking using 100×100-km spatial grid to avoid possible overfitting;<br />
</li>
<li><a href="https://mlr.mlr-org.com/articles/tutorial/feature_selection.html">Feature selection</a> and model-parameter fine-tuning using random and sequential backward search;</li>
</ol>
<p>For more details on how were the models fitted refer to: <a href="https://github.com/soilspectroscopy/ossl-models" class="uri">https://github.com/soilspectroscopy/ossl-models</a>.</p>
<p>For standard global soil spectral calibration models we use various calibration frameworks including:</p>
<ol style="list-style-type: decimal">
<li>Using only MIR spectra for calibration.<br />
</li>
<li>Using only VisNIR spectra for calibration.<br />
</li>
<li>Using combination of MIR and VisNIR spectra.<br />
</li>
<li>Using combination of MIR and VisNIR spectra + geographic covariates.</li>
</ol>
<p>The methods 1 &amp; 2 are standard methods described in literature <span class="citation">(<a href="#ref-malone2021soil" role="doc-biblioref">Wadoux et al. 2021</a>)</span>. The methods
3 &amp; 4 are referred to as the <em>“MIR-VisNIR fusion”</em> approach <span class="citation">(<a href="#ref-vohland2022quantification" role="doc-biblioref">Vohland et al. 2022</a>)</span>.
The method 4 is the <em>“field-specific calibration approach”</em>; we refer to it here
as the <em>“bundle approach”</em> as we basically use all information available
to help produce best predictions of targeted soil properties.</p>
<p>Users can choose to opt for one of the multiple calibration models, which also
depends on the type of data (VisNIR, MIR, coordinates and depths known yes/no) used of course.
The online callibration service (<a href="https://engine.soilspectroscopy.org" class="uri">https://engine.soilspectroscopy.org</a>) and the API
can be used for predicting values of soil properties for smaller datasets (&lt;1000 rows).</p>
<p>Soil spectral scans obtained by different spectroscopic instruments often cannot be
modeled or analyzed together i.e. they require some kind of calibration <span class="citation">(<a href="#ref-lei2022achieving" role="doc-biblioref">Lei and Sun 2022</a>)</span>
before one can fit cross-instrument / cross-dataset calibration models.
In the OSSL library we thus use also instrument / dataset code as the indicator variable.
The most complex models currently in the OSSL are, thus, one with which users need to define both:</p>
<ol style="list-style-type: decimal">
<li>Input MIR spectra,</li>
<li>Input VisNIR spectra (same samples),</li>
<li>Geographical location and soil depth,</li>
<li>Instrument code / dataset code;</li>
</ol>
</div>
<div id="using-default-ossl-models-to-predict-soil-properties" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Using default OSSL models to predict soil properties</h2>
<p>OSSL model registry (RDS) S3 file services currently includes large number of
prediction models fitted for a list of soil properties. The complete list is available in the file <strong><a href="https://github.com/soilspectroscopy/ossl-models">OSSL_models_meta.csv</a></strong>.</p>
<div id="predicting-soil-properties-using-mir-spectra" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Predicting soil properties using MIR spectra</h3>
<p>For example, to predict <a href="https://soilspectroscopy.github.io/ossl-manual/database.html#oc_usda.calc_wpct">soil organic carbon weight percent</a> (<code>oc_usda.calc_wpct</code>) using MIR spectra, we need to load
two models (1) principal component model <code>mpca_mir_kssl_v1.rds</code>,
(2) mlr model for predicting <code>oc_usda.calc_wpct</code>:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="reference-soil-spectroscopy-models.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&#39;./R/ossl_functions.R&#39;</span>)</span>
<span id="cb50-2"><a href="reference-soil-spectroscopy-models.html#cb50-2" aria-hidden="true" tabindex="-1"></a>rep <span class="ot">=</span> <span class="st">&quot;http://s3.us-east-1.wasabisys.com/soilspectroscopy/ossl_models/&quot;</span></span>
<span id="cb50-3"><a href="reference-soil-spectroscopy-models.html#cb50-3" aria-hidden="true" tabindex="-1"></a>pcm1 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/mpca_mir_kssl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb50-4"><a href="reference-soil-spectroscopy-models.html#cb50-4" aria-hidden="true" tabindex="-1"></a>eml1 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;log..oc_usda.calc_wpct/mir_mlr..eml_kssl_na_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb50-5"><a href="reference-soil-spectroscopy-models.html#cb50-5" aria-hidden="true" tabindex="-1"></a>ossl.pca.mir <span class="ot">=</span> <span class="fu">readRDS</span>(pcm1)</span>
<span id="cb50-6"><a href="reference-soil-spectroscopy-models.html#cb50-6" aria-hidden="true" tabindex="-1"></a>ossl.model <span class="ot">=</span> <span class="fu">readRDS</span>(eml1)</span></code></pre></div>
<p>Note that the models (RDS files) can be between 10 to 200 MB in size, depending on complexity of models
and the size of the training data used.</p>
<p>The Principal Component Analysis is described in the <a href="https://github.com/soilspectroscopy/ossl-models/">OSSL models repository</a>.
It is a standard way of compressing 1000+ spectral bands before predictive modeling <span class="citation">(<a href="#ref-chang2001near" role="doc-biblioref">Chang et al. 2001</a>)</span>.
We use the first 60 PCA components for further modeling, which is an arbitrary decisions.</p>
<p>We can look at the summary of model by typing:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="reference-soil-spectroscopy-models.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ossl.model<span class="sc">$</span>learner.model<span class="sc">$</span>super.model<span class="sc">$</span>learner.model)</span></code></pre></div>
<pre><code>Residuals:
    Min      1Q  Median      3Q     Max 
-3.1506 -0.0525  0.0181  0.0661  3.2965 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -0.038545   0.001042  -36.98   &lt;2e-16 ***
regr.ranger    0.235387   0.004115   57.20   &lt;2e-16 ***
regr.xgboost  -0.046506   0.003291  -14.13   &lt;2e-16 ***
regr.cvglmnet  0.470197   0.004078  115.30   &lt;2e-16 ***
regr.cubist    0.362526   0.003946   91.88   &lt;2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.1539 on 57400 degrees of freedom
Multiple R-squared:  0.9821,    Adjusted R-squared:  0.9821 
F-statistic: 7.857e+05 on 4 and 57400 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This shows that the model is an ensemble Machine Learning model based on stacking of
four individual models: <code>regr.ranger</code> (Random Forest) <span class="citation">(<a href="#ref-wright2017ranger" role="doc-biblioref">Wright and Ziegler 2017</a>)</span>, <code>regr.xgboost</code> (Gradient Boosting) <span class="citation">(<a href="#ref-chen2015xgboost" role="doc-biblioref">Chen et al. 2015</a>)</span>,
<code>regr.cvglmnet</code> (Lasso and Elastic-Net Regularized GLM) <span class="citation">(<a href="#ref-friedman2010" role="doc-biblioref">Friedman, Hastie, and Tibshirani 2010</a>)</span> and <code>regr.cubist</code> (Cubist) <span class="citation">(<a href="#ref-kuhn2012cubist" role="doc-biblioref">Kuhn et al. 2012</a>)</span>. The RMSE
of the model is 0.1539 (R-square = 0.982), based on 5-fold Cross Validation with spatial blocking (global grid with 100 km blocks).
Model is based on 57,400 training points.</p>
<p>We can take a look at the accuracy plot for this model:</p>
<div class="figure"><span id="fig:ac-soc1"></span>
<img src="http://s3.us-east-1.wasabisys.com/soilspectroscopy/ossl_models/log..oc_usda.calc_wpct/ap.mir_mlr..eml_kssl_na_v1.rds.png" alt="Accuracy plot for `log..oc_usda.calc_wpct/mir_mlr..eml_kssl_na_v1.rds`." width="70%" />
<p class="caption">
Figure 5.1: Accuracy plot for <code>log..oc_usda.calc_wpct/mir_mlr..eml_kssl_na_v1.rds</code>.
</p>
</div>
<p>Next, we load the sample MIR data that we can use to predict soil organic carbon:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="reference-soil-spectroscopy-models.html#cb53-1" aria-hidden="true" tabindex="-1"></a>mir.raw <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;./sample-data/sample_mir_data.csv&quot;</span>)[,<span class="sc">-</span><span class="dv">1</span>]</span></code></pre></div>
<p>This is a simple table with raw MIR spectral data (absorbances) prepared as a table.
The column names contain the wavelengths / MIR channels:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="reference-soil-spectroscopy-models.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(mir.raw)</span>
<span id="cb54-2"><a href="reference-soil-spectroscopy-models.html#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="do">## 20  1765</span></span>
<span id="cb54-3"><a href="reference-soil-spectroscopy-models.html#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mir.raw[,<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>])</span></code></pre></div>
<pre><code>&#39;data.frame&#39;:   20 obs. of  10 variables:
 $ X4001.656: num  0.411 0.357 0.296 0.152 0.238 ...
 $ X3999.728: num  0.411 0.357 0.297 0.152 0.239 ...
 $ X3997.799: num  0.411 0.357 0.297 0.153 0.239 ...
 $ X3995.871: num  0.411 0.357 0.298 0.153 0.24 ...
 $ X3993.942: num  0.411 0.357 0.298 0.153 0.24 ...
 $ X3992.014: num  0.411 0.357 0.299 0.154 0.241 ...
 $ X3990.085: num  0.411 0.358 0.299 0.154 0.242 ...
 $ X3988.156: num  0.412 0.358 0.299 0.154 0.242 ...
 $ X3986.228: num  0.412 0.358 0.3 0.154 0.243 ...
 $ X3984.3  : num  0.411 0.358 0.3 0.155 0.243 ...</code></pre>
<p>We can generate predictions by using:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="reference-soil-spectroscopy-models.html#cb56-1" aria-hidden="true" tabindex="-1"></a>pred.oc <span class="ot">=</span> <span class="fu">predict.ossl</span>(<span class="at">t.var=</span><span class="st">&quot;log..oc_usda.calc_wpct&quot;</span>, <span class="at">mir.raw=</span>mir.raw, </span>
<span id="cb56-2"><a href="reference-soil-spectroscopy-models.html#cb56-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">ossl.model=</span>ossl.model, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),</span>
<span id="cb56-3"><a href="reference-soil-spectroscopy-models.html#cb56-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">ossl.pca.mir=</span>ossl.pca.mir)</span></code></pre></div>
<p>where <code>ylim=c(0,100)</code> specifies that the prediction values need to be in the range 0 to 100 (values out of these range will be replaced with either 0 or 100).
The output of this model consists of four parts:</p>
<pre><code>List of 4
 $ pred :&#39;data.frame&#39;:  20 obs. of  5 variables:
 $ x    :&#39;data.frame&#39;:  20 obs. of  68 variables:
 $ model:&#39;data.frame&#39;:  57405 obs. of  5 variables:
 $ cf   : num 0.901</code></pre>
<ol style="list-style-type: decimal">
<li>Predictions with back-transformed value and lower and upper prediction intervals (1 std.);</li>
<li>Data frame with all covariate layers needed to generate predictions;</li>
<li>Summary meta-learner with predicted and observed values;</li>
<li>Ratio between variance in predictions produced using base learners and MSE;</li>
</ol>
<p>The predictions are in the format:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="reference-soil-spectroscopy-models.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pred.oc<span class="sc">$</span>pred)</span></code></pre></div>
<pre><code>&#39;data.frame&#39;:   20 obs. of  5 variables:
 $ pred.mean : num  -0.0278 0.0463 0.2844 0.7926 -0.0312 ...
 $ pred.error: num  0.131 0.199 0.111 0.186 0.211 ...
 $ tpred.mean: num  0 0.0474 0.3289 1.209 0 ...
 $ lower.1std: num  NA NA 0.189 0.834 NA ...
 $ upper.1std: num  0.109 0.278 0.485 1.66 0.197 ...</code></pre>
<p>which means that the predicted <code>oc_usda.calc_wpct</code> for first row is 0 etc. The
<code>lower.1std</code> and <code>upper.1std</code> indicate standard prediction interval based on the
prediction error derived in the log-space. For higher values of <code>oc_usda.calc_wpct</code>
prediction interval gets thus proportionally higher for larger absolute values e.g. for row 14 it is between 27% and 34%:</p>
<pre><code>#pred.oc$pred[14,]
   pred.mean pred.error tpred.mean lower.1std upper.1std
14  3.441673  0.1139194   30.23918   26.87566   34.00856</code></pre>
<p>Finally, we can check how well does the new data (MIR scans) reflect the training
data used to build the calibration models:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="reference-soil-spectroscopy-models.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(hexbin)</span>
<span id="cb61-2"><a href="reference-soil-spectroscopy-models.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(grid)</span>
<span id="cb61-3"><a href="reference-soil-spectroscopy-models.html#cb61-3" aria-hidden="true" tabindex="-1"></a>ossl.pcax.mir <span class="ot">=</span> <span class="fu">readRDS</span>(<span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/pca_mir_kssl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>))</span>
<span id="cb61-4"><a href="reference-soil-spectroscopy-models.html#cb61-4" aria-hidden="true" tabindex="-1"></a>reds <span class="ot">=</span> <span class="fu">colorRampPalette</span>(RColorBrewer<span class="sc">::</span><span class="fu">brewer.pal</span>(<span class="dv">9</span>, <span class="st">&quot;YlOrRd&quot;</span>)[<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb61-5"><a href="reference-soil-spectroscopy-models.html#cb61-5" aria-hidden="true" tabindex="-1"></a>hb <span class="ot">&lt;-</span> <span class="fu">hexbin</span>(ossl.pcax.mir<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">xbins=</span><span class="dv">60</span>)</span>
<span id="cb61-6"><a href="reference-soil-spectroscopy-models.html#cb61-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">plot</span>(hb, <span class="at">colramp =</span> reds, <span class="at">main=</span><span class="st">&#39;PCA MIR KSSL&#39;</span>)</span>
<span id="cb61-7"><a href="reference-soil-spectroscopy-models.html#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">pushHexport</span>(p<span class="sc">$</span>plot.vp)</span>
<span id="cb61-8"><a href="reference-soil-spectroscopy-models.html#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.points</span>(pred.oc<span class="sc">$</span>x<span class="sc">$</span>mir.PC1, pred.oc<span class="sc">$</span>x<span class="sc">$</span>mir.PC2, <span class="at">pch=</span><span class="dv">17</span>)</span></code></pre></div>
<div class="figure"><span id="fig:pca-sim"></span>
<img src="img/pca_similarity_plot.png" alt="Similary plot new spectra vs training spectra (PC biplot)." width="80%" />
<p class="caption">
Figure 5.2: Similary plot new spectra vs training spectra (PC biplot).
</p>
</div>
<p>Based on the plot shown above, it appears that some of scans used are less typical
and hence prediction results should be taken with caution.</p>
</div>
<div id="predicting-soil-properties-using-mir-spectra-and-geographical-covariates" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Predicting soil properties using MIR spectra and geographical covariates</h3>
<p>Next, we can also predict values at new location using calibration model that is
field-specific i.e. we use MIR spectra in combination with geographic covariates.
To predict with such data we also need to load geographical locations for the same
MIR scans:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="reference-soil-spectroscopy-models.html#cb62-1" aria-hidden="true" tabindex="-1"></a>new.soil <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;./sample-data/sample_soilsite_data.csv&quot;</span>)</span>
<span id="cb62-2"><a href="reference-soil-spectroscopy-models.html#cb62-2" aria-hidden="true" tabindex="-1"></a>lon <span class="ot">=</span> new.soil<span class="sc">$</span>longitude.std.decimal.degrees</span>
<span id="cb62-3"><a href="reference-soil-spectroscopy-models.html#cb62-3" aria-hidden="true" tabindex="-1"></a>lat <span class="ot">=</span> new.soil<span class="sc">$</span>latitude.std.decimal.degrees</span>
<span id="cb62-4"><a href="reference-soil-spectroscopy-models.html#cb62-4" aria-hidden="true" tabindex="-1"></a>hzn_depth <span class="ot">=</span> new.soil<span class="sc">$</span>lay_depth_to_top <span class="sc">+</span> (new.soil<span class="sc">$</span>lay_depth_to_bottom <span class="sc">-</span> new.soil<span class="sc">$</span>lay_depth_to_top)<span class="sc">/</span><span class="dv">2</span></span></code></pre></div>
<p>This now comes with three additional columns <code>lon</code> and <code>lat</code> and soil depth <code>hzn_depth</code>, which is
the middle of the top and bottom depth of the soil horizon. To predict with then specify also the additional
arguments in the function:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="reference-soil-spectroscopy-models.html#cb63-1" aria-hidden="true" tabindex="-1"></a>eml2 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;log..oc_usda.calc_wpct/mir_mlr..eml_kssl_ll_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb63-2"><a href="reference-soil-spectroscopy-models.html#cb63-2" aria-hidden="true" tabindex="-1"></a>ossl.model <span class="ot">=</span> <span class="fu">readRDS</span>(eml2) </span>
<span id="cb63-3"><a href="reference-soil-spectroscopy-models.html#cb63-3" aria-hidden="true" tabindex="-1"></a>pred.oc2 <span class="ot">=</span> <span class="fu">predict.ossl</span>(<span class="at">t.var=</span><span class="st">&quot;log..oc_usda.calc_wpct&quot;</span>, <span class="at">mir.raw=</span>mir.raw, <span class="at">ossl.model=</span>ossl.model, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),</span>
<span id="cb63-4"><a href="reference-soil-spectroscopy-models.html#cb63-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">ossl.pca.mir=</span>ossl.pca.mir, <span class="at">geo.type=</span><span class="st">&quot;ll&quot;</span>, <span class="at">lon=</span>lon, <span class="at">lat=</span>lat, <span class="at">hzn_depth=</span>hzn_depth, <span class="at">cog.dir=</span><span class="st">&quot;/data/WORLDCLIM/&quot;</span>)</span></code></pre></div>
<p>This type of prediction is somewhat more complex as the function <code>predict.ossl</code> needs also to overlay
points (<code>lon</code> and <code>lat</code>) vs some 62 GeoTIFFs (containing <a href="https://www.worldclim.org/data/worldclim21.html">WorldClim2.1</a> layers and <a href="https://doi.org/10.5281/zenodo.1420114">MODIS LST</a> layers). In this case the layers are located on a local machine, which significantly speeds up predictions function.</p>
<p>We can look at the variable importance table to try to understand how much the
additional geographical covariate layers help with producing predictions:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="reference-soil-spectroscopy-models.html#cb64-1" aria-hidden="true" tabindex="-1"></a>xl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">importance =</span> ossl.model<span class="sc">$</span>learner.model<span class="sc">$</span>base.models[[<span class="dv">1</span>]]<span class="sc">$</span>learner.model<span class="sc">$</span>variable.importance)</span>
<span id="cb64-2"><a href="reference-soil-spectroscopy-models.html#cb64-2" aria-hidden="true" tabindex="-1"></a>xl<span class="sc">$</span>relative_importance <span class="ot">=</span> <span class="dv">100</span><span class="sc">*</span>xl<span class="sc">$</span>importance<span class="sc">/</span><span class="fu">sum</span>(xl<span class="sc">$</span>importance)</span>
<span id="cb64-3"><a href="reference-soil-spectroscopy-models.html#cb64-3" aria-hidden="true" tabindex="-1"></a>xl <span class="ot">=</span> xl[<span class="fu">order</span>(xl<span class="sc">$</span>importance, <span class="at">decreasing =</span> <span class="cn">TRUE</span>),]</span>
<span id="cb64-4"><a href="reference-soil-spectroscopy-models.html#cb64-4" aria-hidden="true" tabindex="-1"></a>xl[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>,]</span></code></pre></div>
<pre><code>                                                      importance relative_importance
mir.PC3                                               5521.13516          44.4468400
mir.PC8                                               1787.82570          14.3925480
mir.PC1                                               1329.03090          10.6991085
hzn_depth                                             1144.91684           9.2169335
mir.PC14                                               236.53609           1.9041884
mir.PC4                                                188.32570           1.5160799
mir.PC2                                                127.37407           1.0254005
mir.PC10                                               118.35989           0.9528336
mir.PC18                                                98.84466           0.7957300
clm_lst_mod11a2.aug.day_m_1km_s0..0cm_2000..2017_v1.0   89.33596           0.7191820
mir.PC7                                                 63.62915           0.5122342
mir.PC17                                                56.04595           0.4511872
mir.PC6                                                 55.01997           0.4429277
mir.PC15                                                54.79086           0.4410833
mir.PC24                                                54.56629           0.4392755
mir.PC11                                                52.60740           0.4235058
clm_lst_mod11a2.feb.day_m_1km_s0..0cm_2000..2017_v1.0   52.41105           0.4219251
mir.PC12                                                41.14582           0.3312366
mir.PC16                                                38.54017           0.3102603
mir.PC9                                                 36.17293           0.2912032</code></pre>
<p>here <code>hzn_depth</code> comes as an important covariate and so is <code>lst_mod11a2.aug.day</code>
(MOD11A long-term meand daily temperature for August). The original MIR PCA components, however,
dominate the prediction model.</p>
<p>The global layers (global land mask at 1-km spatial resolution) are listed at <a href="https://github.com/soilspectroscopy/ossl-models" class="uri">https://github.com/soilspectroscopy/ossl-models</a> and are available as a Cloud-service / Cloud-Optimized GeoTIFFs. The process of spatial overlay for new prediction locations, however, can significantly increase
prediction time, so something to be aware of.</p>
</div>
<div id="predicting-soil-properties-using-visnir-spectra" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Predicting soil properties using VisNIR spectra</h3>
<p>We can also load VisNIR spectra (reflectances) and predict values using the same function:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="reference-soil-spectroscopy-models.html#cb66-1" aria-hidden="true" tabindex="-1"></a>visnir.raw <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;./sample-data/sample_visnir_data.csv&quot;</span>)[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)]</span>
<span id="cb66-2"><a href="reference-soil-spectroscopy-models.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(visnir.raw[,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<pre><code>&#39;data.frame&#39;:   20 obs. of  5 variables:
 $ X350: num  0.0855 0.0677 0.2319 0.3179 0.25 ...
 $ X351: num  0.0839 0.0666 0.2305 0.3195 0.2504 ...
 $ X352: num  0.0816 0.0647 0.2277 0.3184 0.2508 ...
 $ X353: num  0.0811 0.0658 0.2261 0.3134 0.2489 ...
 $ X354: num  0.082 0.0674 0.2258 0.3124 0.2464 ...</code></pre>
<p>We load another PCA model that we prepared using global VisNIR data and the
mlr-model that was fitted using VisNIR data:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="reference-soil-spectroscopy-models.html#cb68-1" aria-hidden="true" tabindex="-1"></a>pmc3 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/mpca_visnir_kssl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb68-2"><a href="reference-soil-spectroscopy-models.html#cb68-2" aria-hidden="true" tabindex="-1"></a>eml3 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;log..oc_usda.calc_wpct/visnir_mlr..eml_ossl_na_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb68-3"><a href="reference-soil-spectroscopy-models.html#cb68-3" aria-hidden="true" tabindex="-1"></a>ossl.pca.visnir <span class="ot">=</span> <span class="fu">readRDS</span>(pmc3)</span>
<span id="cb68-4"><a href="reference-soil-spectroscopy-models.html#cb68-4" aria-hidden="true" tabindex="-1"></a>ossl.model <span class="ot">=</span> <span class="fu">readRDS</span>(eml3)</span>
<span id="cb68-5"><a href="reference-soil-spectroscopy-models.html#cb68-5" aria-hidden="true" tabindex="-1"></a>pred.oc3 <span class="ot">=</span> <span class="fu">predict.ossl</span>(<span class="at">t.var=</span><span class="st">&quot;log..oc_usda.calc_wpct&quot;</span>, <span class="at">visnir.raw=</span>visnir.raw, <span class="at">ossl.model=</span>ossl.model,</span>
<span id="cb68-6"><a href="reference-soil-spectroscopy-models.html#cb68-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>), <span class="at">spc.type =</span> <span class="st">&quot;visnir&quot;</span>, <span class="at">ossl.pca.visnir =</span> ossl.pca.visnir)</span></code></pre></div>
<p>This model is similar to the MIR model, but the accuracy plot indicates that the accuracy
might be significantly lower:</p>
<div class="figure"><span id="fig:ac-soc2"></span>
<img src="http://s3.us-east-1.wasabisys.com/soilspectroscopy/ossl_models/log..oc_usda.calc_wpct/ap.visnir_mlr..eml_ossl_na_v1.rds.png" alt="Accuracy plot for `log..oc_usda.calc_wpct/visnir_mlr..eml_ossl_na_v1.rds`." width="70%" />
<p class="caption">
Figure 5.3: Accuracy plot for <code>log..oc_usda.calc_wpct/visnir_mlr..eml_ossl_na_v1.rds</code>.
</p>
</div>
</div>
<div id="importing-soil-spectral-scans-using-raw-data-formats" class="section level3" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Importing soil spectral scans using raw data formats</h3>
<p>The examples shown above demonstrate prediction results based on using sample
MIR and VisNIR data (csv files). If you only have raw spectral scan data such as
<a href="http://support.asdi.com/Document/Viewer.aspx?id=95">ASD</a> (PAN Analytics Inc.) and/or
<a href="https://www.bruker.com/en/products-and-solutions/infrared-and-raman/opus-spectroscopy-software.html">OPUS files</a> (Bruker Inc.),
you can use various R packages to read files and prepare them for prediction required by OSSL.</p>
<p>Consider for example a sample OPUS file from the <a href="https://registry.opendata.aws/afsis/">AfSIS-1 project</a>,
which is an original file from the Bruker_Alpha_ZnSe instrument. We can read this file
thanks to the <a href="https://philipp-baumann.github.io/simplerspec">simplerspec package</a> by using:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="reference-soil-spectroscopy-models.html#cb69-1" aria-hidden="true" tabindex="-1"></a>mir.x <span class="ot">=</span> simplerspec<span class="sc">::</span><span class="fu">read_opus_bin_univ</span>(<span class="st">&#39;sample-data/icr056141.0&#39;</span>)</span></code></pre></div>
<pre><code>## Extracted spectra data from file: &lt;icr056141.0&gt;</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="reference-soil-spectroscopy-models.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(mir.x)</span></code></pre></div>
<pre><code>##  [1] &quot;metadata&quot;          &quot;spc&quot;               &quot;spc_nocomp&quot;       
##  [4] &quot;sc_sm&quot;             &quot;sc_rf&quot;             &quot;ig_sm&quot;            
##  [7] &quot;ig_rf&quot;             &quot;wavenumbers&quot;       &quot;wavenumbers_sc_sm&quot;
## [10] &quot;wavenumbers_sc_rf&quot;</code></pre>
<p>which gives a list of object including <code>spc</code> which are the spectral bands:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="reference-soil-spectroscopy-models.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(mir.x[[<span class="st">&quot;spc&quot;</span>]])</span></code></pre></div>
<pre><code>## [1]    1 1715</code></pre>
<p>we can plot the MIR absorbance curve for this scan by using:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="reference-soil-spectroscopy-models.html#cb75-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(mir.x[[<span class="st">&quot;spc&quot;</span>]]))</span>
<span id="cb75-2"><a href="reference-soil-spectroscopy-models.html#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(<span class="at">y=</span><span class="fu">as.vector</span>(<span class="fu">t</span>(mir.x[[<span class="st">&quot;spc&quot;</span>]])), <span class="at">x=</span>x,</span>
<span id="cb75-3"><a href="reference-soil-spectroscopy-models.html#cb75-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">3</span>),</span>
<span id="cb75-4"><a href="reference-soil-spectroscopy-models.html#cb75-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&#39;l&#39;</span>, </span>
<span id="cb75-5"><a href="reference-soil-spectroscopy-models.html#cb75-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Wavelength&quot;</span>, </span>
<span id="cb75-6"><a href="reference-soil-spectroscopy-models.html#cb75-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Absorbance&quot;</span></span>
<span id="cb75-7"><a href="reference-soil-spectroscopy-models.html#cb75-7" aria-hidden="true" tabindex="-1"></a>        )</span></code></pre></div>
<div class="figure"><span id="fig:plot-opus"></span>
<img src="025-modeling_files/figure-html/plot-opus-1.png" alt="Spectral absorbances plot using MIR data." width="90%" />
<p class="caption">
Figure 5.4: Spectral absorbances plot using MIR data.
</p>
</div>
<p>This dataset is hence ready to generate predictions using global OSSL models. We can,
for example generate prediction of soil pH using the following model:</p>
<div class="figure"><span id="fig:ac-ph1"></span>
<img src="http://s3.us-east-1.wasabisys.com/soilspectroscopy/ossl_models/ph.h2o_usda.4c1_index/ap.mir_mlr..eml_ossl_ll_v1.rds.png" alt="Accuracy plot for `ph.h2o_usda.4c1_index/mir_mlr..eml_ossl_ll_v1.rds`." width="70%" />
<p class="caption">
Figure 5.5: Accuracy plot for <code>ph.h2o_usda.4c1_index/mir_mlr..eml_ossl_ll_v1.rds</code>.
</p>
</div>
<p>in this case we need to add also lon-lat coordinates and specify the soil depth:</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="reference-soil-spectroscopy-models.html#cb76-1" aria-hidden="true" tabindex="-1"></a>pcm3 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/mpca_mir_ossl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb76-2"><a href="reference-soil-spectroscopy-models.html#cb76-2" aria-hidden="true" tabindex="-1"></a>eml3 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;ph.h2o_usda.4c1_index/mir_mlr..eml_ossl_ll_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb76-3"><a href="reference-soil-spectroscopy-models.html#cb76-3" aria-hidden="true" tabindex="-1"></a>ossl.pca.mir <span class="ot">=</span> <span class="fu">readRDS</span>(pcm3)</span>
<span id="cb76-4"><a href="reference-soil-spectroscopy-models.html#cb76-4" aria-hidden="true" tabindex="-1"></a>ossl.model <span class="ot">=</span> <span class="fu">readRDS</span>(eml3)</span>
<span id="cb76-5"><a href="reference-soil-spectroscopy-models.html#cb76-5" aria-hidden="true" tabindex="-1"></a>pred.ph1 <span class="ot">=</span> <span class="fu">predict.ossl</span>(<span class="at">t.var=</span><span class="st">&quot;ph.h2o_usda.4c1_index&quot;</span>, <span class="at">mir.raw=</span>mir.x[[<span class="st">&quot;spc&quot;</span>]], <span class="at">ossl.model=</span>ossl.model, </span>
<span id="cb76-6"><a href="reference-soil-spectroscopy-models.html#cb76-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">ossl.pca.mir=</span>ossl.pca.mir, <span class="at">geo.type=</span><span class="st">&quot;ll&quot;</span>, <span class="at">lon=</span><span class="fl">28.50299833</span>, <span class="at">lat=</span><span class="sc">-</span><span class="fl">13.10194667</span>, <span class="at">hzn_depth=</span><span class="dv">10</span>, </span>
<span id="cb76-7"><a href="reference-soil-spectroscopy-models.html#cb76-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">cog.dir=</span><span class="st">&quot;/data/WORLDCLIM/&quot;</span>, <span class="at">dataset.code_ascii_c=</span><span class="st">&quot;AFSIS1.SSL&quot;</span>)</span></code></pre></div>
<p>which gives us predictions of <code>ph.h2o_usda.4c1_index</code>:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="reference-soil-spectroscopy-models.html#cb77-1" aria-hidden="true" tabindex="-1"></a>pred.ph1<span class="sc">$</span>pred</span></code></pre></div>
<pre><code>  pred.mean pred.error lower.1std upper.1std
1  8.077812   1.507783   6.570029   9.585594</code></pre>
<p>Note that we had to now specify that this MIR data is from AfSIS project via the
<code>AFSIS1.SSL</code> argument.</p>
<p>Likewise, we can also read the ASD files using the <a href="https://github.com/pierreroudier/asdreader">asdreader package</a>, so we can
generate predictions using VisNIR spectra. Consider for example the sample data
from the KSSL VisNIR repository:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="reference-soil-spectroscopy-models.html#cb79-1" aria-hidden="true" tabindex="-1"></a>asd.raw <span class="ot">=</span> <span class="fu">as.data.frame</span>(asdreader<span class="sc">::</span><span class="fu">get_spectra</span>(<span class="st">&quot;sample-data/101453MD01.asd&quot;</span>))</span>
<span id="cb79-2"><a href="reference-soil-spectroscopy-models.html#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(asd.raw)</span></code></pre></div>
<pre><code>## [1]    1 2151</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="reference-soil-spectroscopy-models.html#cb81-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(asd.raw))</span>
<span id="cb81-2"><a href="reference-soil-spectroscopy-models.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(<span class="at">y=</span><span class="fu">as.vector</span>(<span class="fu">t</span>(asd.raw)), <span class="at">x=</span>x,</span>
<span id="cb81-3"><a href="reference-soil-spectroscopy-models.html#cb81-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.7</span>),</span>
<span id="cb81-4"><a href="reference-soil-spectroscopy-models.html#cb81-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">&#39;l&#39;</span>, </span>
<span id="cb81-5"><a href="reference-soil-spectroscopy-models.html#cb81-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Wavelength&quot;</span>, </span>
<span id="cb81-6"><a href="reference-soil-spectroscopy-models.html#cb81-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Reflectance&quot;</span></span>
<span id="cb81-7"><a href="reference-soil-spectroscopy-models.html#cb81-7" aria-hidden="true" tabindex="-1"></a>        )</span></code></pre></div>
<div class="figure"><span id="fig:plot-ads"></span>
<img src="025-modeling_files/figure-html/plot-ads-1.png" alt="Spectral reflectance plot using VisNIR data." width="90%" />
<p class="caption">
Figure 5.6: Spectral reflectance plot using VisNIR data.
</p>
</div>
<p>we can also directly predict <code>ph.h2o_usda.4c1_index</code> by using:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="reference-soil-spectroscopy-models.html#cb82-1" aria-hidden="true" tabindex="-1"></a>pmc3 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/mpca_visnir_kssl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb82-2"><a href="reference-soil-spectroscopy-models.html#cb82-2" aria-hidden="true" tabindex="-1"></a>eml4 <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;ph.h2o_usda.4c1_index/visnir_mlr..eml_ossl_na_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb82-3"><a href="reference-soil-spectroscopy-models.html#cb82-3" aria-hidden="true" tabindex="-1"></a>ossl.pca.visnir <span class="ot">=</span> <span class="fu">readRDS</span>(pmc3)</span>
<span id="cb82-4"><a href="reference-soil-spectroscopy-models.html#cb82-4" aria-hidden="true" tabindex="-1"></a>ossl.model <span class="ot">=</span> <span class="fu">readRDS</span>(eml4)</span>
<span id="cb82-5"><a href="reference-soil-spectroscopy-models.html#cb82-5" aria-hidden="true" tabindex="-1"></a>pred.ph2 <span class="ot">=</span> <span class="fu">predict.ossl</span>(<span class="at">t.var=</span><span class="st">&quot;ph.h2o_usda.4c1_index&quot;</span>, <span class="at">visnir.raw=</span>asd.raw, </span>
<span id="cb82-6"><a href="reference-soil-spectroscopy-models.html#cb82-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ossl.model=</span>ossl.model, <span class="at">spc.type=</span><span class="st">&quot;visnir&quot;</span>, <span class="at">ossl.pca.visnir=</span>ossl.pca.visnir)</span>
<span id="cb82-7"><a href="reference-soil-spectroscopy-models.html#cb82-7" aria-hidden="true" tabindex="-1"></a>pred.ph2<span class="sc">$</span>pred</span></code></pre></div>
<pre><code>  pred.mean pred.error lower.1std upper.1std
1  6.565335  0.4353427   6.129993   7.000678</code></pre>
<p>We are currently building an API that will work directly with standard raw files
coming directly from the instruments. This should help make the OSSL more robust
and applicable to thousands of requests on a daily basis.</p>
<p>Wrongly formatted spectral scans can lead to artifacts and should be used with care.
Note that complexity of soil spectral scans remains high, including the file sizes that are
difficult to open and read (few thousands of columns)
and are often not supported in standard tabular software e.g. LibreOffice or similar.
We recommend thus to report any issues you might have via our <a href="https://github.com/soilspectroscopy">project GitHub</a> so we
can all help each other produce more accurate primary soil data.</p>
</div>
<div id="the-bundle-approach-to-soil-spectroscopy-calibration" class="section level3" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> The bundle approach to soil spectroscopy calibration</h3>
<p>One of the approaches used to calibrate soil spectroscopy data in the Soil Spectroscopy
for Global Good project is to use a combination of VisNIR, MIR, spatial location
and Earth Observation data, basically any additional information that could potentially
help with calibration. We refer to this as the <em>“bundle approach”</em>. The key
assumption of the bundle approach is that accuracy of predictions could be somewhat
improved, which is especially important for soil organic carbon monitoring and similar.
Some previous research e.g. by <span class="citation"><a href="#ref-vohland2022quantification" role="doc-biblioref">Vohland et al.</a> (<a href="#ref-vohland2022quantification" role="doc-biblioref">2022</a>)</span> and <span class="citation"><a href="#ref-hong2022fusion" role="doc-biblioref">Hong et al.</a> (<a href="#ref-hong2022fusion" role="doc-biblioref">2022</a>)</span> indicate
that such fusion techniques could help improve accuracy of, especially, <em>in-situ</em> methods.</p>
<p>Because several of the training data sets, especially the KSSL and ICRAF-ISRIC,
come with both VisNIR and MIR scans, and are documented in detail, we were able
to fit global calibration models that can now be used to predict soil properties from a combination of data.</p>
<p>Consider for example a sample from North Dakota with a profile code <code>S2014ND095001</code>, and
sample code <code>235157</code> (classified as <em>“Fine-loamy, mixed, superactive, frigid Calcic Hapludoll”</em>).
This sample was taken at location lon=-99.2064444; lat=48.8000056; and covers
the depth interval 101–125 cm (B2 horizon). We can predict value of soil pH by
using both VisNIR and MIR spectra:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="reference-soil-spectroscopy-models.html#cb84-1" aria-hidden="true" tabindex="-1"></a>mir.x <span class="ot">=</span> simplerspec<span class="sc">::</span><span class="fu">read_opus_bin_univ</span>(<span class="st">&#39;sample-data/235157XS01.0&#39;</span>)</span></code></pre></div>
<pre><code>## Extracted spectra data from file: &lt;235157XS01.0&gt;</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="reference-soil-spectroscopy-models.html#cb86-1" aria-hidden="true" tabindex="-1"></a>asd.raw <span class="ot">=</span> <span class="fu">as.data.frame</span>(asdreader<span class="sc">::</span><span class="fu">get_spectra</span>(<span class="st">&quot;sample-data/235157MD01.asd&quot;</span>))</span></code></pre></div>
<p>This time we need to load 2 PCA models (1) for VisNIR and (2) MIR spectra, and one
model for the bundle calibration <code>visnir.mir_mlr..eml_ossl_na_v1.rds</code>:</p>
<p>To make the prediction, we need to specify multiple inputs:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="reference-soil-spectroscopy-models.html#cb87-1" aria-hidden="true" tabindex="-1"></a>pcm.m <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/mpca_mir_ossl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb87-2"><a href="reference-soil-spectroscopy-models.html#cb87-2" aria-hidden="true" tabindex="-1"></a>pcm.v <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;pca.ossl/mpca_visnir_ossl_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb87-3"><a href="reference-soil-spectroscopy-models.html#cb87-3" aria-hidden="true" tabindex="-1"></a>eml.b <span class="ot">=</span> <span class="fu">url</span>(<span class="fu">paste0</span>(rep, <span class="st">&quot;ph.h2o_usda.4c1_index/visnir.mir_mlr..eml_ossl_na_v1.rds&quot;</span>), <span class="st">&quot;rb&quot;</span>)</span>
<span id="cb87-4"><a href="reference-soil-spectroscopy-models.html#cb87-4" aria-hidden="true" tabindex="-1"></a>ossl.pca.mir <span class="ot">=</span> <span class="fu">readRDS</span>(pcm.m)</span>
<span id="cb87-5"><a href="reference-soil-spectroscopy-models.html#cb87-5" aria-hidden="true" tabindex="-1"></a>ossl.pca.visnir <span class="ot">=</span> <span class="fu">readRDS</span>(pcm.v)</span>
<span id="cb87-6"><a href="reference-soil-spectroscopy-models.html#cb87-6" aria-hidden="true" tabindex="-1"></a>ossl.model <span class="ot">=</span> <span class="fu">readRDS</span>(eml.b)</span>
<span id="cb87-7"><a href="reference-soil-spectroscopy-models.html#cb87-7" aria-hidden="true" tabindex="-1"></a>pred.ph.b <span class="ot">=</span> <span class="fu">predict.ossl</span>(<span class="at">t.var=</span><span class="st">&quot;ph.h2o_usda.4c1_index&quot;</span>, <span class="at">spc.type=</span><span class="st">&quot;visnir.mir&quot;</span>, </span>
<span id="cb87-8"><a href="reference-soil-spectroscopy-models.html#cb87-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">mir.raw=</span>mir.x[[<span class="st">&quot;spc&quot;</span>]], <span class="at">visnir.raw=</span>asd.raw, </span>
<span id="cb87-9"><a href="reference-soil-spectroscopy-models.html#cb87-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">ossl.model=</span>ossl.model, <span class="at">ossl.pca.mir=</span>ossl.pca.mir,  </span>
<span id="cb87-10"><a href="reference-soil-spectroscopy-models.html#cb87-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">ossl.pca.visnir=</span>ossl.pca.visnir, <span class="at">hzn_depth=</span><span class="dv">113</span>)</span></code></pre></div>
<p>which gives:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="reference-soil-spectroscopy-models.html#cb88-1" aria-hidden="true" tabindex="-1"></a>pred.ph.b<span class="sc">$</span>pred</span></code></pre></div>
<pre><code>  pred.mean pred.error lower.1std upper.1std
1  8.453564  0.3284695   8.125094   8.782034</code></pre>
<p>We can look at the model prediction accuracy based on 5-fold cross-validation:</p>
<pre><code>summary(ossl.model$learner.model$super.model$learner.model)
Call:
stats::lm(formula = f, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5169 -0.2364  0.0394  0.2470  3.4846 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -0.159098   0.015687 -10.142  &lt; 2e-16 ***
regr.ranger    0.487147   0.008804  55.330  &lt; 2e-16 ***
regr.xgboost  -0.038330   0.007740  -4.952 7.36e-07 ***
regr.cvglmnet  0.297675   0.005977  49.807  &lt; 2e-16 ***
regr.cubist    0.286002   0.004804  59.534  &lt; 2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.4726 on 42324 degrees of freedom
Multiple R-squared:  0.8228,    Adjusted R-squared:  0.8228 
F-statistic: 4.913e+04 on 4 and 42324 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This shows that the model has an RMSE of 0.47, which seems to be the <a href="https://github.com/soilspectroscopy/ossl-models">best performing model</a>
for predicting soil pH from spectral scans. Thus, in this specific case, also the
prediction error shows relatively narrow range of uncertainty.</p>
<div class="figure"><span id="fig:ac-phm"></span>
<img src="http://s3.us-east-1.wasabisys.com/soilspectroscopy/ossl_models/ph.h2o_usda.4c1_index/ap.visnir.mir_mlr..eml_ossl_na_v1.rds.png" alt="Accuracy plot for `ph.h2o_usda.4c1_index/visnir.mir_mlr..eml_ossl_na_v1.rds` the VisNIR-MIR combination." width="70%" />
<p class="caption">
Figure 5.7: Accuracy plot for <code>ph.h2o_usda.4c1_index/visnir.mir_mlr..eml_ossl_na_v1.rds</code> the VisNIR-MIR combination.
</p>
</div>
<p>The bundle approach in the OSSL is used at the moment by default for all soil
variables, although one should keep in mind that the training points are more
patchy i.e. are less representative of the global conditions. As more and more
training data is added to the OSSL, we should be able to serve more representative
calibration models.</p>
<p>The bundle approach could be further extended to using also e.g.:</p>
<ul>
<li>spatial covariates (e.g. WorldClim layers),<br />
</li>
<li>bare-Earth Spectra <span class="citation">(<a href="#ref-dematte2020bare" role="doc-biblioref">Demattê et al. 2020</a>)</span>,<br />
</li>
<li>soil moisture daily estimates (matching the date of soil sampling) <span class="citation">(<a href="#ref-brocca2019sm2rain" role="doc-biblioref">Brocca et al. 2019</a>)</span>,</li>
</ul>
<p>More and more layers will be gradually added to the OSSL registry to enable users to
increase accuracy of their predictions. For updates in the OSSL model library
please subscribe to our channels to stay up-to-date.</p>
</div>
</div>
<div id="registering-your-own-model" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Registering your own model</h2>
<p>If you plan to contribute your own models to the Soil Spectroscopy for Global Good project
please follow these steps:</p>
<ol style="list-style-type: decimal">
<li>We recommend registering and sharing new models via S3 file
service system (e.g. via OpenGeoHub’s Wasabi.com cloud-service) with RDS files produced using
<a href="https://github.com/nuest/docker-reproducible-research">Dockerized solution for full scientific reproducibility</a>.<br />
</li>
<li>For each model the following metadata need to be supplied:
<ul>
<li>Registered <a href="https://hub.docker.com/r/opengeohub/r-geo">docker image</a>; which should specify in detail: software in
use, R package versions etc;</li>
<li>DOI of the zenodo repository with a back-up for the data (i.e. how to cite your models);</li>
<li>URL for accessing the RDS file via S3;</li>
</ul></li>
</ol>
<p>We can host your models on our infrastructure at no additional costs. Please
<a href="https://soilspectroscopy.org/contact/">contact us</a> and apply for registering your models via soilspectroscopy.org.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-brocca2019sm2rain" class="csl-entry">
Brocca, Luca, Paolo Filippucci, Sebastian Hahn, Luca Ciabatta, Christian Massari, Stefania Camici, Lothar Schüller, Bojan Bojkov, and Wolfgang Wagner. 2019. <span>“Sm2rain–ASCAT (2007–2018): Global Daily Satellite Rainfall Data from ASCAT Soil Moisture Observations.”</span> <em>Earth System Science Data</em> 11 (4): 1583–1601. <a href="https://doi.org/10.5194/essd-11-1583-2019">https://doi.org/10.5194/essd-11-1583-2019</a>.
</div>
<div id="ref-chang2001near" class="csl-entry">
Chang, Cheng-Wen, David Laird, Maurice J Mausbach, and Charles R Hurburgh Jr. 2001. <span>“Near-Infrared Reflectance Spectroscopy–Principal Components Regression Analyses of Soil Properties.”</span> <em>Soil Science Society of America Journal</em> 65 (2): 480. <a href="https://doi.org/10.2136/sssaj2001.652480x">https://doi.org/10.2136/sssaj2001.652480x</a>.
</div>
<div id="ref-chen2015xgboost" class="csl-entry">
Chen, Tianqi, Tong He, Michael Benesty, Vadim Khotilovich, Yuan Tang, Hyunsu Cho, and others. 2015. <span>“<span class="nocase">Xgboost: extreme gradient boosting</span>.”</span> <em>CRAN R-Project</em>. <a href="https://cran.r-project.org/package=xgboost">https://cran.r-project.org/package=xgboost</a>.
</div>
<div id="ref-dematte2020bare" class="csl-entry">
Demattê, José AM, José Lucas Safanelli, Raul Roberto Poppiel, Rodnei Rizzo, Nélida Elizabet Quiñonez Silvero, Wanderson de Sousa Mendes, Benito Roberto Bonfatti, et al. 2020. <span>“Bare Earth’s Surface Spectra as a Proxy for Soil Resource Monitoring.”</span> <em>Scientific Reports</em> 10 (1): 1–11. <a href="https://doi.org/10.1038/s41598-020-61408-1">https://doi.org/10.1038/s41598-020-61408-1</a>.
</div>
<div id="ref-friedman2010" class="csl-entry">
Friedman, Jerome, Trevor Hastie, and Robert Tibshirani. 2010. <span>“<span class="nocase">Regularization Paths for Generalized Linear Models via Coordinate Descent</span>.”</span> <em>Journal of Statistical Software</em> 33 (1): 1–22. <a href="https://doi.org/10.18637/jss.v033.i01">https://doi.org/10.18637/jss.v033.i01</a>.
</div>
<div id="ref-hong2022fusion" class="csl-entry">
Hong, Yongsheng, Muhammad Abdul Munnaf, Angela Guerrero, Songchao Chen, Yaolin Liu, Zhou Shi, and Abdul Mounem Mouazen. 2022. <span>“Fusion of Visible-to-Near-Infrared and Mid-Infrared Spectroscopy to Estimate Soil Organic Carbon.”</span> <em>Soil and Tillage Research</em> 217: 105284. <a href="https://doi.org/10.1016/j.still.2021.105284">https://doi.org/10.1016/j.still.2021.105284</a>.
</div>
<div id="ref-kuhn2012cubist" class="csl-entry">
Kuhn, Max, Steve Weston, Chris Keefer, and Nathan Coulter. 2012. <span>“Cubist Models for Regression.”</span> <em>CRAN R-Project</em>. <a href="https://cran.r-project.org/package=Cubist">https://cran.r-project.org/package=Cubist</a>.
</div>
<div id="ref-lei2022achieving" class="csl-entry">
Lei, Tong, and Da-Wen Sun. 2022. <span>“Achieving Joint Calibration of Soil Vis-NIR Spectra Across Instruments, Soil Types and Properties by an Attention-Based Spectra Encoding-Spectra/Property Decoding Architecture.”</span> <em>Geoderma</em> 405: 115449. <a href="https://doi.org/10.1016/j.geoderma.2021.115449">https://doi.org/10.1016/j.geoderma.2021.115449</a>.
</div>
<div id="ref-vohland2022quantification" class="csl-entry">
Vohland, Michael, Bernard Ludwig, Michael Seidel, and Christopher Hutengs. 2022. <span>“<span class="nocase">Quantification of soil organic carbon at regional scale: Benefits of fusing vis-NIR and MIR diffuse reflectance data are greater for in situ than for laboratory-based modelling approaches</span>.”</span> <em>Geoderma</em> 405: 115426. <a href="https://doi.org/10.1016/j.geoderma.2021.115426">https://doi.org/10.1016/j.geoderma.2021.115426</a>.
</div>
<div id="ref-malone2021soil" class="csl-entry">
Wadoux, A. M. J. C., B. Malone, A. B. McBratney, M. Fajardo, and B. Minasny. 2021. <em><span class="nocase">Soil Spectral Inference with R: Analysing Digital Soil Spectra Using the R Programming Environment</span></em>. Progress in Soil Science. Springer International Publishing.
</div>
<div id="ref-wright2017ranger" class="csl-entry">
Wright, Marvin N, and Andreas Ziegler. 2017. <span>“<span class="nocase">ranger: A Fast Implementation of Random Forests for High Dimensional Data in C++ and R</span>.”</span> <em>Journal of Statistical Software</em> 77 (1): 1–17. <a href="https://doi.org/10.18637/jss.v077.i01">https://doi.org/10.18637/jss.v077.i01</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="database.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/soilspectroscopy/ossl-manual/edit/main/025-modeling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["OSSL_book.pdf", "OSSL_book.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"info": true,
"toolbar": {
"position": "fixed"
},
"includes": {
"in_header": "social.html"
}
});
});
</script>

</body>

</html>
